import React from 'react';
import { useNavigate } from 'react-router-dom';

const LandingPage = () => {
  const navigate = useNavigate();

  const handleStart = () => {
    navigate('/detect');
  };

  return (
    <div className="container">
      <h1>Welcome to LLM Text Detector</h1>
      <p style={{ fontSize: '18px', marginBottom: '40px', color: '#555' }}>
        Identify whether the text you see is written by a Human or generated by an AI model like GPT-3.  
        Our Hybrid Detection System ensures high accuracy across different LLMs.
      </p>
      <button onClick={handleStart}>Get Started</button>
    </div>
  );
};

export default LandingPage;
