import React from 'react';
import { useNavigate } from 'react-router-dom';

const LandingPage = () => {
  const navigate = useNavigate();
  return (
    <div className="container">
      <h1>🔍 LLM Text Detector</h1>
      <p style={{ fontSize: '18px', margin: '30px 0' }}>
        Uncover whether your text was written by a human or generated by an AI like ChatGPT, Gemini, or Claude using our hybrid detection model.
      </p>
      <button onClick={() => navigate('/detect')}>Get Started</button>
    </div>
  );
};

export default LandingPage;
